In [4]:
cd ..

C:\Users\fcc\Desktop\git_tweet\SBSPS-Challenge-2598-Twitter-Sentiment-Analysis

In [1]:
#importing libraries
import pandas as pd
import numpy as np
import string
import re
import nltk
from textblob import TextBlob
from wordcloud import WordCloud
import matplotlib.pyplot as plt
from PolaritySubjectivity import *

In [18]:
df=pd.read_csv('covidtweets.csv')
pd.set_option('display.max_colwidth', 100)
df.head()

,Unnamed: 0,Unnamed: 0.1,usernameTweet,ID,text,url,nbr_retweet,nbr_favorite,nbr_reply,datetime,is_reply,is_retweet,user_id,has_media,medias,Unnamed: 14,Unnamed: 15
0,0,0,rj_ashwin,1.243960e+18,"Sabse Pehle toh Majdur , Labour Class, Worker,kehna band Karo Unhe Tum Kya ho jo 'Work from h...",/rj_ashwin/status/1243959777266286593,0,1,0,2020-03-28 23:24:57,False,False,2.898097e+09,NaN,NaN,NaN,NaN
1,1,1,vikramsoni232,1.244163e+18,@ TajinderBagga Bhaiya i proud of you. You are real hero in delhi in #lockdown21 You moral ...,/vikramsoni232/status/1244163016012075008,0,0,0,2020-03-29 12:52:33,False,False,2.915966e+08,NaN,NaN,NaN,NaN
2,2,2,ABHISHE33329022,1.244291e+18,Mam India mein hum ko company's ki audit krni chiye.wo labour ko pay kre lock down ki salary...,/ABHISHE33329022/status/1244290847236972544,0,0,0,2020-03-29 21:20:30,True,False,1.244170e+18,NaN,NaN,NaN,NaN
3,3,3,hindust74474485,1.253172e+18,Videsh me rahne wale Bhai India laye Gaye but Jo log India me hi dusre state me fase huye h ...,/hindust74474485/status/1253171675081904129,0,0,0,2020-04-23 09:29:44,False,False,1.252877e+18,NaN,NaN,NaN,NaN
4,4,4,KumarSa61420257,1.254602e+18,Akhir bhojh ban gaye na bihari pure India pe. Students bhi and Labour bhi.Jab bihari majdur...,/KumarSa61420257/status/1254602420426063872,0,0,0,2020-04-27 08:15:01,False,False,9.912317e+17,NaN,NaN,NaN,NaN

In [19]:
# Dropping unnecessary columns

df_clean = df.drop(['Unnamed: 0','Unnamed: 14','Unnamed: 15','medias','has_media','user_id','url','ID'], axis=1)
df_clean.rename(columns={'text':'Tweets'}, inplace=True)
print(df_clean.shape)
df_clean.head()

(74553, 9)

,Unnamed: 0.1,usernameTweet,Tweets,nbr_retweet,nbr_favorite,nbr_reply,datetime,is_reply,is_retweet
0,0,rj_ashwin,"Sabse Pehle toh Majdur , Labour Class, Worker,kehna band Karo Unhe Tum Kya ho jo 'Work from h...",0,1,0,2020-03-28 23:24:57,False,False
1,1,vikramsoni232,@ TajinderBagga Bhaiya i proud of you. You are real hero in delhi in #lockdown21 You moral ...,0,0,0,2020-03-29 12:52:33,False,False
2,2,ABHISHE33329022,Mam India mein hum ko company's ki audit krni chiye.wo labour ko pay kre lock down ki salary...,0,0,0,2020-03-29 21:20:30,True,False
3,3,hindust74474485,Videsh me rahne wale Bhai India laye Gaye but Jo log India me hi dusre state me fase huye h ...,0,0,0,2020-04-23 09:29:44,False,False
4,4,KumarSa61420257,Akhir bhojh ban gaye na bihari pure India pe. Students bhi and Labour bhi.Jab bihari majdur...,0,0,0,2020-04-27 08:15:01,False,False

In [20]:
df_clean['Subjectivity'] = df_clean['Tweets'].apply(getSubjectivity)
df_clean['Polarity'] = df_clean['Tweets'].apply(getPolarity)
df_clean['Analysis'] = df_clean['Polarity'].apply(getAnalysis)

In [28]:
dataStore = pd.DataFrame()
dataStore['Datetime'] = df_clean['datetime']
dataStore['Tweets'] =df_clean['Tweets']
dataStore['Subjectivity'] = df_clean['Subjectivity']
dataStore['Polarity'] = df_clean['Polarity']
dataStore['Analysis'] = df_clean['Analysis']
dataStore.head()

,Datetime,Tweets,Subjectivity,Polarity,Analysis
0,2020-03-28 23:24:57,"Sabse Pehle toh Majdur , Labour Class, Worker,kehna band Karo Unhe Tum Kya ho jo 'Work from h...",0.000000,0.000000,Neutral
1,2020-03-29 12:52:33,@ TajinderBagga Bhaiya i proud of you. You are real hero in delhi in #lockdown21 You moral ...,0.404167,0.258333,Positive
2,2020-03-29 21:20:30,Mam India mein hum ko company's ki audit krni chiye.wo labour ko pay kre lock down ki salary...,0.288889,-0.155556,Negative
3,2020-04-23 09:29:44,Videsh me rahne wale Bhai India laye Gaye but Jo log India me hi dusre state me fase huye h ...,0.000000,0.000000,Neutral
4,2020-04-27 08:15:01,Akhir bhojh ban gaye na bihari pure India pe. Students bhi and Labour bhi.Jab bihari majdur...,0.500000,0.214286,Positive

In [33]:
dataStore.to_csv('PolaritySubjectivity.csv')

In [30]:
p_tweets = df_clean[df_clean['Analysis']=='Positive']
p_tweets_per = round(p_tweets.shape[0]/df_clean.shape[0] * 100, 3)

n_tweets = df_clean[df_clean['Analysis']=='Negative']
n_tweets_per = round(n_tweets.shape[0]/df_clean.shape[0] * 100, 3)

In [31]:
# # I have created the graph below using Tableau, but it can be also done using matplotlib here


# # Plot the polarity and subjectivity

# plt.figure(figsize = (20,20))
# plt.scatter(df_clean['Polarity'], df_clean['Subjectivity'], color='Blue')

# plt.title('Scatter Plot',fontsize = 40,fontweight='bold')
# plt.xlabel('Polarity',fontsize = 30)
# plt.ylabel('Subjectivity',fontsize =30)
# plt.xticks(fontsize=17)
# plt.yticks(fontsize=17)
# plt.savefig('Polarity vs Subjectivity (Scatter Plot)',dpi=300)
# plt.show()

In [32]:
# # Plot analysis count
# plt.title('Bar Plot')
# plt.xlabel('Sentiments')
# plt.ylabel('Count')
# df_clean['Analysis'].value_counts().plot(kind='bar')
# plt.savefig('Polarity vs Subjectivity (Bar Plot)',dpi=300)
# plt.show()